# Server properties
server:
  port: 8081
# Spring Properties
spring:
  kafka:
    consumer:
      client-id: employee-consumer
      bootstrap-servers: localhost:9094
      group-id: employee-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
# Swagger properties
springdoc:
  show-actuator: true